[package]
name = "thingsboard_mapper"
version = "0.1.0"
edition = "2021"

[dependencies]
rumqttc = "0.24"
serde_json = "1.0"
tokio = { version = "1.37", features = ["full"] }
futures = "0.3"

[features]
thingsboard = []
